### ISSUE TITLE
Using 1x1 filters with HWCE of GAP8

### ISSUE THREAD

**Issue by jinhuang01** [GreenWaves-Technologies/gap_sdk#10]
Hi, we are using GAP8 to deploy our ML models for some real world applications. However, in our model, there are some 1x1 filters. In the document of GAP8 and the header file "CNN_HwCE.h/.c", we only find out it accepts 1/2/3 3x3 filters or 1 5x5 filters or 1 4x7 filters for one cycle. Therefore, we decide to write our own codes for 1x1 filters. We would like to know whether HWCE accepts 1x1 filters in its hardware design and whether there is any advice for doing that?

**Comment by Yaooooo** [comment]
Hi, thank you for your question. Exactly, the HWCE is not designed for such calculation. BUT, we can still do something to make HWCE do such job. We can do maximum 3x1x1 in 1 cycle. The method is convert 3 1x1 convolutions to 3x3x3 convolutions. To do that, you need to re-build a matrix filter 3*9 like this:
{
 filter_value1, 0, 0, 0, 0, 0, 0, 0,\
 filter_value2, 0, 0, 0, 0, 0, 0, 0,\
 filter_value3, 0, 0, 0, 0, 0, 0, 0
}

FYI, all the HWCE apis and libraries have been packaged in our "autotiler" tool. However, this mode has not been supported yet.

Hope this could help you.
Best,
Yao
