### ISSUE TITLE
Workload distribution in the cluster.

### ISSUE THREAD

**Issue by Olivier-Dopeli** [GreenWaves-Technologies/gap_sdk#111]
Hello,

Currently, I'm watching the execution on the GAPuino of the nntool/mnist example . And I have some questions about how the cluster works. 

I understood that the Conv2D and MaxPooling layers are running on HWConvolutionEngine, but are the other 8 RISC-V cores in "idle mode" during this time?
 
And in the case of Dense Layer, is the execution parallelized between the 8 RISC-V cores of the cluster?

Thank you in advance.

**Comment by sousoux** [comment]
The HWCE only supports certain convolutions. If usable then it will be used. While it is operating the other cluster cores will be clock gated if they are idle. All the NN kernels are at a minimum parallelized on the cluster cores. The only thing that the FC will be doing during network execution is managing transfers from external memory delegated by the cluster code.
