### ISSUE TITLE
Hwce problem for WaterMeter application

### ISSUE THREAD

**Issue by Nuvey81** [GreenWaves-Technologies/gap_sdk#125]
Hi,
I am trying to make the WaterMeter example works but i have some issues : 
When i do a "make", i have the error "_make: *** [.../gap_sdk/applications/WaterMeter/BUILD/GAP8_V2/GCC_RISCV//.../gap_sdk/tools/autotiler_v2/generators/CNN/kernels/src/CNN_HwCE.o] Error 1_" ('...' is for the gap_sdk localisation).

I think i have this problem because of CNN_HwCE.c. Some headers functions may not be up to date ? (I have "make" errors like "_error: too few arguments to function 'hwce_gen_config0_set'
  hwce_gen_config0_set("_ ).

Furthermore, i succed to make it works when i removing the line "_PULP_APP_SRCS += $(MNIST_KER_PATH)/src/CNN_HwCE.c_" from the Makefile.

Thanks for your help

**Comment by Yaooooo** [comment]
Hi,

I have reproduced your problem, there's a bug in this application when using HWCE. 
We will fix it, and let you know when it's fixed.

Thanks a lot for your report.
