### ISSUE TITLE
unable to run hello world example! plus another MAJOR request

### ISSUE THREAD

**Issue by tp19021** [GreenWaves-Technologies/gap_sdk#131]
I tried running 'make clean all run' for testing Hello World example but I am getting this error regarding the makefile where it can't recognize the pmsis_rules.mk file.

Makefile:9: /pmsis_rules.mk: No such file or directory
make: *** No rule to make target '/pmsis_rules.mk'. Stop

How do I fix this? 

Also do you know where I can find any multilayer NN examples and how to use nntool to map them to the GAP8? Also to view performance counters for such benchmarks?

**Comment by tp19021** [comment]
To add to the hello world issue, the 1st time I run, this is the error:
![error_log](https://user-images.githubusercontent.com/56482928/83166819-5d470580-a107-11ea-8fe0-b7031550a8d5.JPG)

**Comment by Pafrak** [comment]
Hi tp19021,
this should solve your problem:
`pip3 install pyelftools`

To read performance counter you can look at this example:
[(https://github.com/GreenWaves-Technologies/gap_sdk/tree/master/examples/pmsis/test_periph/perf)
]

For NNtool you can take a look at the readme: [https://github.com/GreenWaves-Technologies/gap_sdk/tree/master/tools/nntool].
