### ISSUE TITLE
Error when building mnist using nn tools

### ISSUE THREAD

**Issue by tp19021** [GreenWaves-Technologies/gap_sdk#132]
in the gap_sdk/examples/nntool/examples/mnist, im trying to compile and run it onto the gap8 but when i run 'make clean all run' im getting an error where it says 'no module named argcomplete' as shown below
![image](https://user-images.githubusercontent.com/56482928/83257262-e9126d80-a1ab-11ea-8778-536c25ac3a46.png)
I tried to install it using pip3 but it says its already installed but I still get the same error afterwards. how do i fix it?

**Comment by Pafrak** [comment]
try pip

**Comment by tp19021** [comment]
so ive tried exiting su and ran make again but now it says it does not recognize tensorflow as shown below:
![image](https://user-images.githubusercontent.com/56482928/83266169-6349ee80-a1ba-11ea-92d6-ed17d107ea66.png)

This is bizarre since ive installed anaconda and the result of make nntool shows that it successfully installed tensorflow 1.14.0 as shown below:
![image](https://user-images.githubusercontent.com/56482928/83266253-7c529f80-a1ba-11ea-902c-de0e9de79101.png)

I tried pip3 install tensorflow anyway but had this error about msgpack and wrapt:
![image](https://user-images.githubusercontent.com/56482928/83266346-9ee4b880-a1ba-11ea-80d2-b3770e39973d.png)

I then tried checking tensorflow by doing pip freeze but it and this is what I got:
![image](https://user-images.githubusercontent.com/56482928/83266556-e53a1780-a1ba-11ea-9706-8e102b07c8f2.png)

Im not sure whats the next step to take exactly to allow the make to work

**Comment by sousoux** [comment]
I think you have probably not run a make sdk in the gap_sdk directory. Make all does not build nntool / autotiler.

**Comment by sousoux** [comment]
Also, check that the anaconda python is actually active. It should be in your bash.rc. which python can help to see what is actually configured.

**Comment by tp19021** [comment]
I did run make nntool and make autotiler separately. I can do make sdk still if thats worth doing

Regarding the anaconda, do I need to activate the environemnt cuz i think i did activate the installation when I was following the installation procedure

**Comment by sousoux** [comment]
Honestly. I'd delete the whole thing and start again. You shouldn't be running the build as root. When you execute sudo you start a new shell so all the exports done in the sourceme are lost. Please delete the directory and follow the readme to the letter.

**Comment by tp19021** [comment]
So I tried doing everyting in su mode, that is install and activate anaconda and then ran make sdk and got this error to do with not finding the version for tensorflow 1.14.0 (the same error when running pip install -r tools nntool/requirements.txt as per gap8 manual):
![image](https://user-images.githubusercontent.com/56482928/83289194-969d7500-a1dc-11ea-9181-977eb616a6ee.png)
