### ISSUE TITLE
How to perform flexible parallelization of CNN layers?

### ISSUE THREAD

**Issue by tp19021** [GreenWaves-Technologies/gap_sdk#137]
I've been reading on the autotiler documentation where it talks about how to use the basic kernels to select between a single core and all 8 cores. Is there a way to parallelize the CNN layers to run on 2 and 4 cores for example? If so, how exactly?

**Comment by sousoux** [comment]
Redefine gap_ncore to fix it at the number of cores that you want to use. See https://github.com/GreenWaves-Technologies/gap_sdk/blob/d69bd408cd70e88446516fc5bd37c5824c2813fc/tools/autotiler_v3/include/GapSystem.h#L52

**Comment by sousoux** [comment]
No. If you look at the kernels gap_ncore is systematically called to determine the parallelism. I must admit that I can't remember if the fork depends on that but any core that has nothing to do will exit the kernel fast and clock gate.

**Comment by tp19021** [comment]
So is it meant to be this trivial to be able to parallelize our benchmarks? Also is there a way to check/verify om the code for applications like cifar10 and mnist that these number of cores will be used? Like a way to print out from a function that tells us so.
________________________________

**Comment by tp19021** [comment]
Would we also need to enable parallel features in the ctrl argument of these CNN generators as shown below for the CNN_convolutionPoolReLu() function? :

[cid:92f70d93-9667-46f4-a0ff-7da3b1da5228]
________________________________

**Comment by Pafrak** [comment]
No, this is just a different tiling and computation strategy, but both versions are parallel.  To verify the core used you have two ways. First is to look at performance you will see a ~2x slow down when using half the core and ~8x slow down when using just one core. So if perf does not change you did not set them properly, otherwise you can take one of the parallel functions and print inside the coreid. All the core that are executing it will print thier own one.

**Comment by tp19021** [comment]
Hi Francesco,

I see thank you for your solution. Regarding your 2nd option, would we need to print inside the definition of the cnn_generators functions used in the model.c file in which the tool generators the kernel.c and .h code from it or would we need to print the core ID inside the kernel.c?
________________________________

**Comment by tp19021** [comment]
I see, thats fine. I can get successful change in power and performance now after chaning gap_ncore() in the #else case. Thank you for the solution!
________________________________
