### ISSUE TITLE
Missing apt-get packages

### ISSUE THREAD

**Issue by ccravens** [GreenWaves-Technologies/gap_sdk#14]
When attempting to build the SDK for the first time on the VirtualBox Ubuntu image, I had to install 2 additional libraries in order to successfully build the SDK:

1) cmake
2) libusb-1.0

After installing these, it appears the SDK built successfully. I suggest adding "cmake libusb-1.0" to the list of apt-get packages on the first step of the README

**Comment by sousoux** [comment]
Hi, apologies for this. We started checking in portions of work that have been done to improve the debug bridge and that does have an effect on the needed packages. I will do this now.

**Comment by ccravens** [comment]
No problem! Thanks! I'm excited to start working with your product
