### ISSUE TITLE
Overclocking GAP8 [question]

### ISSUE THREAD

**Issue by sderrien** [GreenWaves-Technologies/gap_sdk#142]
Hello,

As a part of a research project, we would like to study how far it is possible to overclock/undervolt the GAP8, and quantity the type of errors that occur under such operating conditions. 

Did anyone already tried this ? Does anyone have an (even very rough) idea of how far it would be possible to push the chip ?

Thanks in advance,

Steven

**Comment by antoine-faravelon** [comment]
Hello,

For  now we are pretty sure you can reach above 250MHz FC frequency, without much trouble. And there's probably quite a bit of margin.
The main limits will first be the hyperbus. As it runs at same frequency as FC, it will stop working above ~150MHz. 
My guess would be that the next part that would fail will be the memory, as it is also following the FC. To push the chip, mostly begin by pushing voltage whenever it fails. Once this does not work anymore, your best bet is to cool it down somehow. It depends how far you want to go.

Please do come back to use when you have results,
Antoine.
