### ISSUE TITLE
Build no longer works after sdk 3.6 upgrade

### ISSUE THREAD

**Issue by tp19021** [GreenWaves-Technologies/gap_sdk#152]
So i've followed the instructions on upgrading the sdk version to 3.6 and after than I tried to build the mnist example but I came across this eror of the module flatbuffers.flexbuffers not found:
![image](https://user-images.githubusercontent.com/56482928/86629392-42e42f80-bfc3-11ea-8b7b-f20f8d0ed69e.png)

I tried installing flexbuffers using pip and pip3 but it doesn't fix the error. I've only started getting this error after this sdk upgrade. Its also the same issue when I try another example like visual_wake. I'm not sure how to fix this?

**Comment by sousoux** [comment]
make sdk
