### ISSUE TITLE
Can we use GAP SDK on MacOS?

### ISSUE THREAD

**Issue by Raven98** [GreenWaves-Technologies/gap_sdk#159]

**Comment by antoine-faravelon** [comment]
Greetings,

We do not currently support MacOS. 
However, you should be able to build the toolchain from here: https://github.com/pulp-platform/pulp-riscv-gnu-toolchain (which has instruction for MacOS build)
And most of the sdk is bash(also compatible with zsh) & python. So in theory you should be able to make it work.
