### ISSUE TITLE
AutoTiler; undefined referencec to 'Load_RNN_SQ8_Library'

### ISSUE THREAD

**Issue by gemenerik** [GreenWaves-Technologies/gap_sdk#169]
First, thanks for providing us with the [GAPflow video](https://www.youtube.com/watch?v=0JtxdWdrMpY&t=159s&ab_channel=GreenWavesTechnologies), it's really helpful for a quick start.

Now, the issue;
Running the latest gap_sdk, went through the tutorial video, managed to create an AutoTiler model out of a simple tflite int8 quantized object detection CNN using CIFAR-10 (following this [tutorial](https://www.tensorflow.org/tutorials/images/cnn)). Saved as h5, converted and quantized using tflite. The first steps of the video work for me, I can load it properly, and successfully create an AutoTiler model. I named the resulting files/folders identical to the tutorial, so have an `ATModel.c` file and a `/tensors` folder.

In the video, the next step is to compile the model using the one-liner;
`gcc ATModel.c -g -o Gentile -I. -I${TILER_INC} -I${TILER_EMU_INC} -I${TILER_CNN_GENERATOR_PATH} -I${TILER_CNN_GENERATOR_PATH_SQ8} -I${NNTOOL_GENERATOR_PATH} -I${TILER_CNN_KERNEL_PATH} -I${TILER_CNN_KERNEL_PATH_SQ8} -I${NNTOOL_KERNELS_PATH} ${TILER_LIB} ${TILER_CNN_GENERATOR_PATH}/CNN_Generator_Util.c ${TILER_CNN_GENERATOR_PATH_SQ8}/CNN_Generators_SQ8.c ${NNTOOL_GENERATOR_PATH}/nntool_extra_generators.c`

I tried this command having sourced both `gap_sdk/configs/ai_deck.sh` (on which I am trying to put the CNN), and `gap_sdk/sourceme.sh`, both result in the same error;

`/tmp/cckfeAyH.o: In function 'tf_modelModel':`
`/home/rik/Documents/cifar10/ATModel.c:32: undefined reference to 'Load_RNN_SQ8_Library'`
`collect2: error: ld returned 1 exit status`

Am I missing a generator/kernel library in the command line?

**Comment by sousoux** [comment]
Hi. Sorry for the problem. The default nntool template tries to load the RNN kernels as well as the CNN ones. It looks like you are missing a source file in your compile line ${TILER_CNN_GENERATOR_PATH_SQ8}/RNN_Generators_SQ8.c. Actually you could use a custom nntool model template and remove the call to Load_RNN_SQ8_Library() from it since the example you are trying is CNN based but adding the file above should solve the issue for you.

**Comment by gemenerik** [comment]
Thanks for the quick reply. That actually makes a lot of sense. I removed the call to load it from the AutoTiler model, and the one-liner ran without error.
