### ISSUE TITLE
Concats with multiple versions of the same input are not supported

### ISSUE THREAD

**Issue by gemenerik** [GreenWaves-Technologies/gap_sdk#176]
Quantized during TensorFlow Lite conversion to a `.tflite` model.
I get the following error loading into `nntool`;

`NotImplementedError: concats with multiple versions of the same input are not supported. This is normally a graph design problem.`
`EXCEPTION of type 'NotImplementedError' occurred with message: 'concats with multiple versions of the same input are not supported. This is normally a graph design problem.'`

I am a bit confused what is meant by this exception. What I can think of is either;

1. Literally what the exception says; I am branching off and concatenating back together. Note that this is desired and not a 'graph design problem' as the exception calls it. Visualized in `netron`:
> ![image](https://user-images.githubusercontent.com/49898887/98663196-106b8a00-2349-11eb-9b3a-e0bdee9eedb7.png)
2. The quantization in the TensorFlow Lite conversion does not only add quantization and dequantization at the network input and output, but adds _requantizations_ in my graph before concatenations, but not on all branches that feed into them. So `nntool` maybe thinks there are different types being fed?

> ![image](https://user-images.githubusercontent.com/49898887/98661747-2710e180-2347-11eb-94ca-fdfbf3332686.png)
> All branches requantized

> ![image](https://user-images.githubusercontent.com/49898887/98661784-32fca380-2347-11eb-807f-07d094709de9.png)
> All but one branch requantized

I truly hope it's not the first one, otherwise the types of networks I am looking at are impossible to implement altogether. At least, for now.

Thanks for the help!

EDIT: Very important to note is that I do not get this error when opening an unquantized tflite model. I am working with 6 channel images and I haven't been able to quantize in `nntool` yet, so I couldn't tell you if the error would occur then. If anyone has some suggestions how to feed representative data to the `aquant` command when one can't work with regular image formats, please share! My preference would be to feed random tensors of set dimensions, as I do in the TensorFlow Lite conversion. What `input_files` formats are supported?

**Comment by gemenerik** [comment]
I managed to get the requantizations on all branches, and the error persists, so it is likely the branching off and concatenating. Still it is curious that the error does not occur when loading an unquantized model, does it not interpret the architecture before?
>![image](https://user-images.githubusercontent.com/49898887/98827500-3d966600-2437-11eb-9c85-d618195a214c.png)

* Since there is, as far as I know, no reasonable workaround; where can I best leave suggestions for features?

**Comment by sousoux** [comment]
Sorry. I only just saw this. Is it possible for you to give us a model with this problem?

**Comment by gemenerik** [comment]
No worries! I am working on a network based on FlowNetS for optical flow estimation.

The following zip includes:
- `models.py` where the model is defined in TensorFlow
- `flownetslike`; a saved model dir with `.pb` saved model
- `flownetslike.tflite`; a converted (quantized) tflite model.

[flownetslike.zip](https://github.com/GreenWaves-Technologies/gap_sdk/files/5596446/flownetslike.zip)

The most important reason to want concatenations of multiple versions of the same input is because it allows one to do optical flow predictions at various resolutions, and concatenate these back onto the feature maps. This is conventional for all state of the art optical flow CNNs, and helps solve the aperture problem while maintaining a high resolution final flow prediction.

**Comment by gemenerik** [comment]
This issue is similar to if not the same as the problem mentioned in the [Jun 4th comment](https://github.com/GreenWaves-Technologies/gap_sdk/issues/127#issuecomment-638641809) by @FrontMage on issue #127

**Comment by sousoux** [comment]
This was a bug. Fixed in sources. Will be pushed shortly.
