### ISSUE TITLE
ONNX bilinear upsampling support

### ISSUE THREAD

**Issue by gemenerik** [GreenWaves-Technologies/gap_sdk#191]
In ONNX opset version 9 and lower ONNX converts bilinear upsampling layers in PyTorch to `Upsample` layers with a 'mode' attribute.
```diff
-EXCEPTION of type 'ValueError' occurred with message: 'no handler found for Upsample'
```

In ONNX opset version 10 and up ONNX converts these to a `Resize` layer, again with a 'mode' attribute
```diff
-EXCEPTION of type 'ValueError' occurred with message: 'no handler found for Resize'
```

Neither is recognized by `nntool` as a bilinear upsampling layer.

**Comment by sousoux** [comment]
Upsample is deprecated since v10. I didn't bother looking at it. I will.

**Comment by sousoux** [comment]
Two interpolation modes: nearest (default), and linear (including bilinear, trilinear, etc)

I love the etc. Implement this packet header witth 1234, etc.

**Comment by sousoux** [comment]
Resize we need to do. We have kernels that support many of its modes. We already handle them from TF.

**Comment by sousoux** [comment]
Could you let me have your graph with 'resize' in it please? I'm particularly interested in something that has the scale tensor rather than the size tensor.

**Comment by sousoux** [comment]
I found something to test against. The importer for resize is implemented. It does have limitations which you can check in nntool with 'help onnx'. It will go to the dev_3.8.0 branch shortly.
