### ISSUE TITLE
HWCE vs NNTool

### ISSUE THREAD

**Issue by Julie33380** [GreenWaves-Technologies/gap_sdk#198]
Hello,

We are looking for HWCE integration with NNTool soft.
The only example that we saw is WaterMeter, but the compilation flow already starts with MnistModel.c (instead of tflite file) which is the normal output of basic NNTool.
Is NNTool compatible with HWCE? and how to set it up?

Thank you,

**Comment by Pafrak** [comment]
hi Julie33380,
 no NNtool does not generate code for HWCE, you have to use Autotiler models as in the water meter example.
