### ISSUE TITLE
Brightness problem with himax camera

### ISSUE THREAD

**Issue by MattAbrs** [GreenWaves-Technologies/gap_sdk#213]
Hello,

I have some issues about the himax camera i use with the gapuino B (gap8).
Indeed, a colleague of mine worked on the same project as me few months ago on the 3.6.1_dev version and obtain this photo with a LCD screen with a brightness of 0:  (don't pay attention about the white square) :
![imgOut0](https://user-images.githubusercontent.com/81748393/115251151-8bbc3d80-a12a-11eb-9dcb-bf33c7d08ae9.jpeg)

Today, i work with the 3.9_dev version and i use the same code as my colleague and i obtain this photo with a LCD screen  with a brightness of 0: 
![Rendu photo](https://user-images.githubusercontent.com/81748393/115251910-48160380-a12b-11eb-9345-bdbcdbc6b1e4.png)

I think the difference between the two photos is about the driver but i'm not sure.
How can i have a brighter photo ?

Thanks for your help.

**Comment by Yaooooo** [comment]
HI @MattAbrs 

In fact, this is a question about how to tune this camera, which unfortunatly we are not expert. 
You can use our driver of himax (here: https://github.com/GreenWaves-Technologies/gap_sdk/tree/master/rtos/pmsis/pmsis_bsp/camera/himax) to set the register of gain, exposure, etc. 
In the driver and our example (https://github.com/GreenWaves-Technologies/gap_sdk/blob/master/examples/pmsis/bsp/cameras/test_camera_io/test_camera_himax.c), we just turn on the auto-exposure and AEG, which takes some time to calibrate. 

Hope this can help you.
