### ISSUE TITLE
Tensorflow requirements not found in the mnist example

### ISSUE THREAD

**Issue by MattAbrs** [GreenWaves-Technologies/gap_sdk#214]
Hi,

I'm actually working on the 3.9_dev SDK version. 
I followed your instructions about the different installations except for the anaconda installation, I didn't do it.

When I try to compile the mnist example, I face some errors because I don't have tensorflow.
Moreover, when I check your different requirements.txt, it's not mentionned in it the tensorflow installation.

So, I'm wondering what tensorflow version should I install to make the mnist example work, and why tensorflow doesn't appear in the requirements file?

Thanks.

**Comment by sousoux** [comment]
Sorry about that. We don't have it in the requirements file because it is really only a requirement for examples. The toolchain doesn't need it. Just installing the latest version python -m pip install tensorflow should work.
