### ISSUE TITLE
VSCode Setup

### ISSUE THREAD

**Issue by qlawyer** [GreenWaves-Technologies/gap_sdk#220]
Hi, 

I want to setup an IDE for GAP8. I was following the setup guide for hello world example [here](https://greenwaves-technologies.com/setting-up-sdk/). I got the following error log in the build process. I described the exact steps I went through below the error log as well.

Executing task: export GAP_RISCV_GCC_TOOLCHAIN=/usr/lib/gap_riscv_toolchain && source /home/osboxes/gap_riscv_toolchain_ubuntu_18/gap_sdk/configs/gap9_v2.sh && make all platform=fpga <

/bin/bash: /home/osboxes/gap_riscv_toolchain_ubuntu_18/gap_sdk/configs/gap9_v2.sh: No such file or directory
The terminal process "/bin/bash '-c', 'export GAP_RISCV_GCC_TOOLCHAIN=/usr/lib/gap_riscv_toolchain && source /home/osboxes/gap_riscv_toolchain_ubuntu_18/gap_sdk/configs/gap9_v2.sh && make all platform=fpga'" failed to launch (exit code: 1).

Press any key to close the terminal.

I can run riscv64-unknown-elf-gdb from terminal, so I assume it is properly added to path. I sourced the sourceme.h, run 'make vscode' in the terminal, it return a .vscode folder which contains a blank script folder, launch, settings, tasks json files. The instruction guide asked me to edit /scripts/build.sh. Since the folder was blank, I created build.sh file, copied make all platform=board in it and saved. 

The next step asked me to edit tasks.json, so made the following changes. 

"command": "/home/osboxes/gap8_openocd/src/openocd -f /home/osboxes/gap8_openocd/tcl/interface/ftdi/olimex-arm-usb-ocd-h.cfg -f /home/osboxes/gap_riscv_toolchain_ubuntu_18/gap_sdk/tools/gap8-openocd-tools/tcl/gap9revb.tcl",

I edited the paths a little different than it is given. There is obviously no openocd.exe, and openocd is present in src folder, that's why i edited like that. tlc folder is not in scripts folder, and olimex-arm-usb-ocd-h.cfg in the path i entered. gap9revb.tlc file does not exist in the toolchain folder, so i just hopelessly plugged sdk path there as it is asked. Finally, I modified "text": "target extended-remote <IP address>:3333" line by plugging ip address that ip addr returns, it is a local 192.168.x.x. I am not sure if it is the ip address that is asked for. 

Then I followed  "Terminal"->"Run Task"->"Build from Makefile"->"Continue without scanning the task output", and it returned the error log I copied. What would you recommend in this case? Thank you for your help in advance.

**Comment by Yaooooo** [comment]
Hi,

Sorry our document is made for internal usage and made for next generation of chip (which hasn't released yet). Therefore, if you want to use VSCode for GAP8, you should adapt these command to your needs, for example:
* should not use this source file: gap9_v2.sh
* should not use the platform=fpga
* You don't need to use the riscv64 gdb.

For now, I just remove this section from the README file, since it's not for GAP8 platform.
You can change a bit to make it work (it should be not complicate), but the gdb cannot work properly with GAP8 because of HW limitation.

Sorry for that.

Yao
