### ISSUE TITLE
Batchnorm not directly after a convolution layer causes nntool error

### ISSUE THREAD

**Issue by neoamos** [GreenWaves-Technologies/gap_sdk#226]
If you have a batchnorm directly after a convolution layer, it gets folded into the convolution by the tflite converter.  If its not after a convolution layer, it adds a multiply and add operator, but this causes the following nntool error:
```
Traceback (most recent call last):
  File "/gap_sdk/tools/nntool/nntool", line 101, in <module>
    main()
  File "/gap_sdk/tools/nntool/nntool", line 85, in main
    mod.generate_code(args)
  File "/gap_sdk/tools/nntool/interpreter/generator.py", line 93, in generate_code
    write_template(G, code_gen, opts['model_directory'], opts['model_file'], code_template, "model")
  File "/gap_sdk/tools/nntool/interpreter/generator.py", line 47, in write_template
    model = template(G, code_generator=code_gen)
  File "/gap_sdk/tools/nntool/generation/default_template.py", line 193, in default_template
    return execute_template(generator_template_v3, G, naming_convension, code_generator)
  File "/gap_sdk/tools/nntool/generation/default_template.py", line 187, in execute_template
    return template_function(G, code_generator)
  File "/gap_sdk/tools/nntool/generation/default_template.py", line 94, in generator_template_v3
    ${gen.kernel_generator(indent=1)}
  File "/gap_sdk/tools/nntool/generation/code_generator.py", line 387, in kernel_generator
    if not self.execute_phase("kernels", node, qrec, in_eparams, out_eparams, cname):
  File "/gap_sdk/tools/nntool/generation/generators/generator_decorators.py", line 79, in execute_phase
    this_res = gen['func'](self, param, qrec, *args, **kwargs)
  File "/gap_sdk/tools/nntool/generation/generators/kernels/mult8/matadd_kernels_generator.py", line 43, in matadd_kernel_generator
    raise ValueError("missing generator: the matrix add generator only handles adds of tensors of the same size")
ValueError: missing generator: the matrix add generator only handles adds of tensors of the same size
```
The definition of the network:

```
def batch_norm(img_width, img_height, img_channels, output_dim):
   # Input
   img_input = Input(shape=(img_height, img_width, img_channels))

   x1 = Conv2D(32, (5, 5), strides=[2,2], padding='same')(img_input)
   x1 = MaxPooling2D(pool_size=(3, 3), strides=[2,2])(x1)

   # First residual block
   x2 = Conv2D(32, (3, 3), strides=[2,2], padding='same')(x1)

   x2 = keras.layers.normalization.BatchNormalization()(x2)
   x2 = Activation('relu')(x2)
   x2 = Conv2D(32, (3, 3), padding='same')(x2)

   x1 = Conv2D(32, (1, 1), strides=[2,2], padding='same')(x1)
   x3 = add([x1, x2])

   # Batch norm not directly after conv causes error
   x3 = keras.layers.normalization.BatchNormalization()(x3)

   x = Flatten()(x3)

   x = Dense(output_dim)(x)
   nums = Activation('softmax')(x)

   model = Model(inputs=[img_input], outputs=[nums])
   print(model.summary())

   return model
```
And a visualization of the tflite network:
![batch norm network](https://i.imgur.com/dlt8rRw.png)

With gap_sdk 3.9.1.  If the input to the batchnorm is larger, tflite converts it to just a multiply operation with no add, and nntool doesn't throw an error.  I don't know exactly what algorithm tflite is using, but it would be nice if the add would be supported so batchnorm works in all cases.

**Comment by sousoux** [comment]
try running fusions -a expression_matcher. Be aware that this feature is still in development and will be updated in the next nntool version. There are issues with it in the current released version.

**Comment by neoamos** [comment]
I'm not sure exactly what you mean by that.  Is it an option for the tflite converter or nntool?  I notice that the add operator is actually only present if the model is trained and not present if its not trained.  I previously said it was not there with larger input, but thats because I wasn't training the model when the input was large.  Maybe the converter optimizes it out if its zeroes.
Here is the tflite file also: 
[model.tflite.gz](https://github.com/GreenWaves-Technologies/gap_sdk/files/6445183/model.tflite.gz)

**Comment by neoamos** [comment]
Oh I understand now, I'm using an example from the AI deck example repo and it has a nntool script with 'fusions --scale8'.  What is the expression_matcher supposed to be?  I can't find any documentation about it.

**Comment by sousoux** [comment]
If you open nntool and type help or help fusions you will get an explanation about that. fusions -l lists all available fusions. fusions -a expression_matcher attempts to fuse piecewise operations into a single kernel. It should be run after the existing script before quantization if you are not importing a quantized graph.

**Comment by gemenerik** [comment]
There is a bug with multiplies followed by an add:

```
Traceback (most recent call last):
  File "/home/rik/gap_sdk_490/tools/nntool/nntool", line 104, in <module>
    main()
  File "/home/rik/gap_sdk_490/tools/nntool/nntool", line 88, in main
    mod.generate_code(args)
  File "/home/rik/gap_sdk_490/tools/nntool/interpreter/generator.py", line 93, in generate_code
    write_template(G, code_gen, opts['model_directory'], opts['model_file'], code_template, "model")
  File "/home/rik/gap_sdk_490/tools/nntool/interpreter/generator.py", line 47, in write_template
    model = template(G, code_generator=code_gen)
  File "/home/rik/gap_sdk_490/tools/nntool/generation/default_template.py", line 199, in default_template
    return execute_template(generator_template_v3, G, naming_convension, code_generator)
  File "/home/rik/gap_sdk_490/tools/nntool/generation/default_template.py", line 193, in execute_template
    return template_function(G, code_generator)
  File "/home/rik/gap_sdk_490/tools/nntool/generation/default_template.py", line 93, in generator_template_v3
    ${gen.kernel_generator(indent=1)}
  File "/home/rik/gap_sdk_490/tools/nntool/generation/code_generator.py", line 511, in kernel_generator
    raise NotImplementedError(f"Don't know how to generate kernel for parameter type {node.name} {node.CLS_OP_NAME}. "
NotImplementedError: Don't know how to generate kernel for parameter type MUL_0_79 mul. Perhaps you need to run fusions -a expression_matcher.
make: *** [../common/model_rules.mk:60: BUILD_MODEL_SQ8BIT/tinyflownetModel.c] Error 1
```

With `fusions -a expression_matcher` I get undefined references to all fused mul/adds
```
/home/rik/avoidFlowNet/visual_wake/BUILD/GAP8_V2/GCC_RISCV_PULPOS/BUILD_MODEL_SQ8BIT/tinyflownetKernels.o: In function `hal_spr_read_then_clr':
/home/rik/gap_sdk_490/install/GAP8_V2/include/pmsis/implem/dma.h:181: undefined reference to `s235_kernel'
/home/rik/gap_sdk_490/install/GAP8_V2/include/pmsis/implem/dma.h:181: undefined reference to `s235_kernel'
/home/rik/gap_sdk_490/install/GAP8_V2/include/pmsis/implem/dma.h:181: undefined reference to `s235_kernel'
```

**Comment by gemenerik** [comment]
I get undefined references to all occasions of mul-add fusion kernels generated with the expression_matcher
```
[...]/BUILD/GAP8_V2/GCC_RISCV_PULPOS/BUILD_MODEL_SQ8BIT/modelKernels.o: In function `hal_spr_read_then_clr':
/home/rik/gap_sdk_490/install/GAP8_V2/include/hal/dma/mchan_v6.h:272: undefined reference to `s241_kernel'
```

**Comment by sousoux** [comment]
Add MODEL_EXPRESSIONS = $(MODEL_BUILD)/Expression_Kernels.c to common.mk. It's done automatically by gen_project. We need to make that more automatic.

**Comment by gemenerik** [comment]
Thank you. 

I've been working with the SDK for quite a while now and have a lot of legacy code in my project. I decided to go for a clean start with gen_project and that seems to have fixed it for me. Nice feature!

**Comment by aqqz** [comment]
I meet this problem seem like this, when I `add fusions -a expression_matcher` to nntool script, and I add `
MODEL_EXPRESSIONS = $(MODEL_BUILD)/Expression_Kernels.c` in model_decl.mk. My SDK version is 4.8.0
here is the error info:
``/home/taozhi/tf2/BUILD/GAP8_V2/GCC_RISCV_PULPOS/BUILD_MODEL_SQ8BIT/modelKernels.o: In function `eu_bar_setup_mask':
/home/taozhi/gap/gap_sdk/install/GAP8_V2/include/pmsis/implem/dma.h:268: undefined reference to `s2_kernel'
/home/taozhi/gap/gap_sdk/install/GAP8_V2/include/pmsis/implem/dma.h:268: undefined reference to `s2_kernel'
/home/taozhi/tf2/BUILD/GAP8_V2/GCC_RISCV_PULPOS/BUILD_MODEL_SQ8BIT/modelKernels.o: In function `rt_team_fork':
/home/taozhi/gap/gap_sdk/install/GAP8_V2/include/pmsis/implem/dma.h:268: undefined reference to `s2_kernel'
collect2: error: ld returned 1 exit status
make: *** [/home/taozhi/gap/gap_sdk/utils/rules/pulp_rules.mk:227：/home/taozhi/tf2/BUILD/GAP8_V2/GCC_RISCV_PULPOS/application] error 1``

**Comment by Jool99** [comment]
> I meet this problem seem like this, when I `add fusions -a expression_matcher` to nntool script, and I add ` MODEL_EXPRESSIONS = $(MODEL_BUILD)/Expression_Kernels.c` in model_decl.mk. My SDK version is 4.8.0 here is the error info: `` /home/taozhi/tf2/BUILD/GAP8_V2/GCC_RISCV_PULPOS/BUILD_MODEL_SQ8BIT/modelKernels.o: In function `eu_bar_setup_mask': /home/taozhi/gap/gap_sdk/install/GAP8_V2/include/pmsis/implem/dma.h:268: undefined reference to `s2_kernel' /home/taozhi/gap/gap_sdk/install/GAP8_V2/include/pmsis/implem/dma.h:268: undefined reference to `s2_kernel' /home/taozhi/tf2/BUILD/GAP8_V2/GCC_RISCV_PULPOS/BUILD_MODEL_SQ8BIT/modelKernels.o: In function `rt_team_fork': /home/taozhi/gap/gap_sdk/install/GAP8_V2/include/pmsis/implem/dma.h:268: undefined reference to `s2_kernel' collect2: error: ld returned 1 exit status make: *** [/home/taozhi/gap/gap_sdk/utils/rules/pulp_rules.mk:227：/home/taozhi/tf2/BUILD/GAP8_V2/GCC_RISCV_PULPOS/application] error 1 ``

If anyone gets the same issue, I solved a similar error by adding:
`MODEL_EXPRESSIONS = $(MODEL_BUILD)/Expression_Kernels.c` in model_decl.mk.

And then making sure to use `MODEL_EXPRESSIONS` in these two lines, that were already there:
```
MODEL_GEN_C = $(addsuffix .c, $(MODEL_GEN)) $(MODEL_EXPRESSIONS)
MODEL_GEN_CLEAN = $(MODEL_GEN_C) $(addsuffix .h, $(MODEL_GEN)) $(MODEL_EXPRESSIONS)
```
