### ISSUE TITLE
camera tests can not capture image

### ISSUE THREAD

**Issue by jtdeng** [GreenWaves-Technologies/gap_sdk#229]
Hi,
When I run this camera test: gap_sdk/examples/native/pulpos/periph/camera/camera_HIMAX
The program was hanging and no pgm image generated

I was running the program on Gapuino board model 1.1 (gapuino_v2.sh), and the output I got was:

-------make clean all run output------
Warn : Interface already configured, ignoring
TARGET create
Info : core 0 selected
0
Info : gap8_adv_debug_itf tap selected
Info : adv_dbg_unit debug unit selected
Info : Option 7 is passed to adv_dbg_unit debug unit
GAP8 INIT TARGET
Info : clock speed 1500 kHz
Info : JTAG tap: gap8.cpu tap/device found: 0x149511c3 (mfg: 0x0e1 (Wintec Industries), part: 0x4951, ver: 0x1)
GAP8 examine target
Init jtag
Initialising GAP8 JTAG TAP
Info : adv debug unit is configured with option BOOT MODE JTAG
Info : adv debug unit is configured with option ADBG_USE_HISPEED
Info : gdb port disabled
Loading binary through JTAG
Info : tcl server disabled
Info : telnet server disabled
Warn : Burst read timed out
Entering main controller
ready to take a photo

-----------------

then endless wait, seems the python test.py was not called to download the image.

the makefile was below:
--------Makefile----------
PULP_APP = test
PULP_APP_FC_SRCS = test.c
PULP_CFLAGS = -O3 -g #-DGVSOC

PLPBRIDGE_FLAGS += -s camera@test.py

include $(INSTALL_DIR)/rules/pulp_rules.mk
----------------------------

Any missing settings or bug of plpbridge?

Thanks

**Comment by Yaooooo** [comment]
Hi 

We stopped the maintance on the plpbridge especially for the image IO part, which may cause some issue in the latest version of SDK.
It's better to switch to latest sdk with openocd. 
For using camera on GAPuino, you can take a look into these examples:
https://github.com/GreenWaves-Technologies/gap_sdk/tree/master/examples/pmsis/bsp/cameras

The example test_camera_io will be a good fit for himax camera.

Yao
