### ISSUE TITLE
Compiling FreeRTOS with the AI Deck 1.1 (GAP8 rev 2)

### ISSUE THREAD

**Issue by freiremelgiz** [GreenWaves-Technologies/gap_sdk#232]
Regarding the Bitcraze AI Deck 1.1, I am having issues running GAP8 examples with FreeRTOS as the PMSIS_OS. It seems that I must select PULPOS instead. However, if I source for example gapuino.sh instead of ai_deck.sh from the gap_sdk, then FreeRTOS works as expected in the AI Deck.

The error I am getting when compiling `gap_sdk/examples/pmsis/helloworld` with PMSIS_OS=freertos is an undefined reference to 'semihost_exit' as well as undefined references to 'semihost_write0' in file 'gap_sdk/rtos/freeRTOS/vendors/gwt/gap8/src/driver/gap_io.c'.

After sourcing `gap_sdk/configs/ai_deck.sh`, the command
`make clean all run PMSIS_OS=freertos platform=board` 
generates the following linking error trace:

```
/~/gap_sdk/examples/pmsis/helloworld/BUILD/GAP8_V2/GCC_RISCV//~/gap_sdk/rtos/freeRTOS/vendors/gwt/gap8/src/device/system_gap8.o: In function `system_init':
/~/gap_sdk/rtos/freeRTOS/vendors/gwt/gap8/src/device/system_gap8.c:130: undefined reference to `semihost_exit'
/~/gap_sdk/examples/pmsis/helloworld/BUILD/GAP8_V2/GCC_RISCV//~/gap_sdk/rtos/freeRTOS/vendors/gwt/gap8/src/driver/gap_io.o: In function `__semihost_buffer_write_exec':
/~/gap_sdk/rtos/freeRTOS/vendors/gwt/gap8/src/driver/gap_io.c:365: undefined reference to `semihost_write0'
/~/gap_sdk/rtos/freeRTOS/vendors/gwt/gap8/src/driver/gap_io.c:365: undefined reference to `semihost_write0'
/~/gap_sdk/rtos/freeRTOS/vendors/gwt/gap8/src/driver/gap_io.c:368: undefined reference to `semihost_write0'
collect2: error: ld returned 1 exit status
make: *** [/~/gap_sdk/rtos/freeRTOS/vendors/gwt/rules/freeRTOS_rules.mk:372: /~/gap_sdk/examples/pmsis/helloworld/BUILD/GAP8_V2/GCC_RISCV/test] Error 1                                           
```
Where I have hidden personal file space information with character `~`.

Again, the command 
`make clean all run PMSIS_OS=pulpos platform=board`
works as expected.

**Comment by Yaooooo** [comment]
Hi @freiremelgiz 

Sorry for our late reply, I have pushed a fix on the branch 4.0_dev, please give a try.
This fix will be merged into master in next release soon.
Regards,

Yao
