### ISSUE TITLE
can't install gap_sdk

### ISSUE THREAD

**Issue by SpeakNow-Wu** [GreenWaves-Technologies/gap_sdk#242]
i'm using ubuntu 20.04，and without the GAP8 board(i just need to use emulator will it influence?).when I install the sdk,this step especially
<img width="684" alt="image" src="https://user-images.githubusercontent.com/63546742/124164786-00034d80-da99-11eb-9116-c6e138c590f6.png">
it shows like
<img width="743" alt="image" src="https://user-images.githubusercontent.com/63546742/124164864-1ad5c200-da99-11eb-8611-ca04f4410648.png">
though I updated sphinx it doesn't work.
and when I tried to run the "helloword" example,it shows
<img width="744" alt="image" src="https://user-images.githubusercontent.com/63546742/124165397-a0597200-da99-11eb-83ae-be784fa66689.png">
until I type "make clean all run platform=gvsoc runner_args=--vcd" it showed the correct result.
what should I do for it. thanks

**Comment by PaulLuperini** [comment]
Hi @SpeakNow-Wu,

Sorry for the documentation generation inconvenience.
It seems that new versions of `breathe` package do not support old versions of `Sphinx`, according to this [issue](https://github.com/sphinx-doc/sphinx/issues/7664).
What is your version of `Sphinx` ?
Could you try to update it with `pip3 install --upgrade Sphinx` ? You may also need to do the same with `breathe`.

We will add more specific versions in `doc/requirements.txt` to avoid this issue.

Your second issue seems to be related to the default selected platform.
By default, the SDK assumes that you are using a board (equivalent to `platform=board`).
If you want to use GVSoC simulator, you need to specify `platform=gvsoc` when doing a `make clean all run`.
So to run the `helloworld` example on GVSoC, use `make clean all run platform=gvsoc`.

If all your questions are answered and your issues fixed, feel free to close this issue.
Thank you for your feedback,
Have a good day :)

**Comment by SpeakNow-Wu** [comment]
hi @PaulLuperini thanks for your response, my Sphinx version is 1.8.5, after I update both sphinx and breathe it still shows the same result. one more silly question, is this software like an application or just I can work it on the terminal? thanks

**Comment by PaulLuperini** [comment]
Weird :thinking: 
What is the output of `sphinx-build --version`?
Can you try to go to the `doc` folder and run `make clean html`?

Can you give me more details about your second question? What is this software you are talking about?
The GAP SDK allows you to create applications that are intended to run on GAP processors, not on your computer.
GVSoC is a tool used to simulate GAP processors, to ease development.

**Comment by PaulLuperini** [comment]
Hi @SpeakNow-Wu,
`1.8.5` is the version of the Ubuntu package `python3-sphinx`. It may be overriding your local python3 packages.
If you installed it, could you try uninstalling it? Is `~/.local/bin` in your `PATH` ?

**Comment by SpeakNow-Wu** [comment]
thank you Paul,  I just run it on Ubuntu 18.04 and it works now, I don't know what happened on 20.04, but the package of sphinx really doesn't work.
