### ISSUE TITLE
Issues with using nntool to generate my own model

### ISSUE THREAD

**Issue by HaolinChen** [GreenWaves-Technologies/gap_sdk#243]
When I try to open my own model.tflite . Error occurs when update graph dimensions.
`graph.dim.MissMatchedInputsError
EXCEPTION of type 'MissMatchedInputsError' occurred with message: ''`
Then when I try to open my own model.onnx. Error occurs too.
`EXCEPTION of type 'BackendIsNotSupposedToImplementIt' occurred with message: 'LeakyRelu version 6 is not implemented.'`

**Comment by sousoux** [comment]
Thanks. This is fixed internally and will be pushed with the next version.

**Comment by sousoux** [comment]
Closed due to innactivity
