### ISSUE TITLE
error in pulpos.all

### ISSUE THREAD

**Issue by SpeakNow-Wu** [GreenWaves-Technologies/gap_sdk#257]
the error happens like that,is this code necessary?and any ideas?
<img width="753" alt="image" src="https://user-images.githubusercontent.com/63546742/126883410-34373a82-f5a4-474d-8e23-a1486c8b3a21.png">
and when i wanna run a example besides "helloworld" it shows like this
<img width="678" alt="image" src="https://user-images.githubusercontent.com/63546742/126883436-c480c31e-b10b-422e-9f40-a84c9ca49da8.png">
why this happens
many thanks

**Comment by Yaooooo** [comment]
Hi, 
If you follow the [README](https://github.com/GreenWaves-Technologies/gap_sdk/blob/master/README.md), you don't need to use these sub-targets for build (like pulpos.all)
For your 2nd problem, "freertos/pulpos" is for you to choose to compile the example in FreeRTOS or pulpOS, therefore, you should run it: 
`make clean all run platform=gvsoc PMSIS_OS=freertos`
