### ISSUE TITLE
NNTool: Permission denied

### ISSUE THREAD

**Issue by HaolinChen** [GreenWaves-Technologies/gap_sdk#259]
I have upgraded to the latest version of SDK, everthing is ok except NNTool.
When I try to run nntool, error occurs.
`gap_sdk/tools/nntool/nntool: Permission denied`
In the /nntool folder, nntool is not even executable.

**Comment by Yaooooo** [comment]
Hi, sorry I just found the file right has been changed to non-executable. I pushed a fix on master, you can pull it.
Otherwise, you can fix it with:
`chmod +x gap_sdk/tools/nntool/nntool`

This should fix your problem. If not, please feel free to reopen this issue.
