### ISSUE TITLE
Programming a sleep signal with the STM8 on Gapoc_b

### ISSUE THREAD

**Issue by MattAbrs** [GreenWaves-Technologies/gap_sdk#288]
Hi,

I wanted to flash and program a Sleep# signal from the STM8 with Gapoc_b v2.3.

I tried to find information or examples on how to do this, but I couldn't find anything. My goal is to have the lowest possible power consumption on the Gapoc with the low power mode of the gap8 and stm8. 

Is there any information on how to use the STM8 (and put it in low power mode) with the Gapoc?

Thanks in advance.

Best regards.

**Comment by Pafrak** [comment]
Hi @MattAbrs ,
 we just released a repository [here](https://github.com/GreenWaves-Technologies/stm8l_utilities) that you can use to program the STM8 running the project in the STM8L_PROGRAM folder and an example on how to control it in the folder STM8L_CTRL.
