### ISSUE TITLE
the possibility of deploying reinforcement learning model

### ISSUE THREAD

**Issue by noahzn** [GreenWaves-Technologies/gap_sdk#293]
Hi, so I'm wondering if any model converted by tflite can be run on the AI deck? I want to train a DQN reinforcement learning algorithm using tf-agents, then convert it with tflite. I'm not sure if it is possible to run the converted model on the AI deck. Thanks.

**Comment by sousoux** [comment]
While the GAP NN toolchain is very sophisticated, 'any' is a big word. I would put an 'm' in front of it. It has to be said that we have not done any work converting RL models so you would be entering new territory and potentially operators that we do not support.
