### ISSUE TITLE
Understanding runtimes for cifar10 and mnist examples

### ISSUE THREAD

**Issue by saseptim** [GreenWaves-Technologies/gap_sdk#32]
Hi

We are trying to evaluate the gap8 and are running the cifar10 and mnist examples.
The output of the cifar10 script is:

Layer0:   14207 Cycles,    4012 instruments
Layer1:   37964 Cycles,   10613 instruments
Layer2:    3077 Cycles,    1194 instruments

We would like the results in units of time. Are "cycles" in the result the number of clock cycles? If so, we should be able to extrapolate time by dividing by the clock frequency. How can we determine at what frequency the gap8 is running then?

Thanks.

**Comment by Yaooooo** [comment]
Hi,

Reposted the answer in gap8_developers group here:
 
Cycles are indeed clock cycles on the cluster. Given that the cluster can run at a maximum of 175MHz you can use that to figure out the shortest possible time to do the operation. The frequency can be scaled dynamically down from this level to allow you to reduce the core voltage and save power.

For further information:
https://greenwaves-technologies.com/manuals/BUILD/PULP-OS/html/group__Freq.html

Best
