### ISSUE TITLE
How to modify the size of HyperRam when using gvsoc?

### ISSUE THREAD

**Issue by paulxiongfree** [GreenWaves-Technologies/gap_sdk#323]
Hello,

I am trying to deploy a network with 512x512 image size on the board with gvsoc for simulation. I am encountering a problem when trying to do allocation on RAM. Take mnist for example, the generated mnistKernal.c file calls the AT_HYOERRAM_ALLOC function to allocate L3 memory. However, when the image is too large, the graph symbol memory needed is large as well. 

So I am wondering is there a possible way to modify some setting of GAP8 configuration file that gvsoc takes as input so that the RAM can be enlarged from64Mbit to maybe 128Mbit. 

Thank you!

**Comment by paulxiongfree** [comment]
Hello! Can someone please help with my problem plz? Thank you!

**Comment by Yaooooo** [comment]
Hi, you can change the size in this config file:
/tools/gap-configs/configs/devices/hyperram.json

But be careful, this is an external ram, if in the future you want to make a board w/ such size, you need to check on the market if you can find this size of hyperram.

**Comment by paulxiongfree** [comment]
I changed the size in that .json file then source and build again. But I still got the same error. The error return is still there. Is there other things I need to do in order to load the modification?
