### ISSUE TITLE
Autotiler not up to date

### ISSUE THREAD

**Issue by ROMAINPC** [GreenWaves-Technologies/gap_sdk#325]
Hi,

I have the same error on every program using NN model.
On the make model I obtain the following error :
`gap_sdk/tools/autotiler_v3/CNN_Generators/CNN_Copy_Generators.c:688 : référence indéfinie vers « GenTilingDebug »`
Here and in all files calling the function.

I assume that the remote library on which the compilation depends is not up to date.  The new functions are therefore absent from the associated .a.

May you verify that thank you.

**Comment by DYX-JL** [comment]
I got the same problem, have you solved it?

**Comment by ROMAINPC** [comment]
Hello,
Yes and no, I just checkout on release 4.12 which does not use these new functions.
