### ISSUE TITLE
NNTOOL load ONNX tensor quantization

### ISSUE THREAD

**Issue by Doraemon-DYX** [GreenWaves-Technologies/gap_sdk#355]
In NNTOOL, it seems that `open -q` can only load TFLITE tensor quantization. So the ONNX tensor quantization can't be loaded by NNTOOL? When I use the command `open -q *.onnx` to load the ONNX tensor quantization, it seems to encounter some errors.

**Comment by sousoux** [comment]
We do load quantisation info from onnx graphs via the fake quantization nodes but I would describe this as an experimental feature both because the quantization info in onnx exports is often incomplete and because there are not that many real graphs to test it on. I would be interested to see the error and, if possible, have the graph generating it.

**Comment by Doraemon-DYX** [comment]
Hi, 
I use the following commands in gap9_sdk environment:
`
open -q mnist.onnx
adjust 
dump 106.ppm -S float
`
Then, I got the error info:
![Screenshot from 2022-10-19 14-15-18](https://user-images.githubusercontent.com/74696799/196611544-9cbf837d-da4e-491f-b6d8-4374803e2e80.png)
Also, I use command `qerror 106.ppm`, I got the error info:
![Screenshot from 2022-10-19 14-18-02](https://user-images.githubusercontent.com/74696799/196611790-aa42bd79-84a2-40a6-8f06-5cdbe6c35b36.png)
Here is my model and input image:
[model.zip](https://github.com/GreenWaves-Technologies/gap_sdk/files/9817383/model.zip)

I tried to debug it, but I haven't got the reason yet.

**Comment by sousoux** [comment]
Wow that is a huge network to do MNIST!

Seems to work for me.

The -S float is not an option for dump. Should be -q (quantize), -d (quantize/dequantize) or nothing (float). -s -1 below prints the last output tensor.

(NNT mnist.onnx 0) dump ~/Downloads/106.ppm  -s -1
output_1
   0.0000    0.0000    0.0000    0.0000    0.0000    0.0000    1.0000    0.0000    0.0000    0.0000 
(NNT mnist.onnx 0) dump ~/Downloads/106.ppm -q  -s -1
output_1
        0         0         0         0         0         0     32767         0         0         0 
(NNT mnist.onnx 0) dump ~/Downloads/106.ppm -d  -s -1
output_1
   0.0000    0.0000    0.0000    0.0000    0.0000    0.0000    1.0000    0.0000    0.0000    0.0000 
(NNT mnist.onnx 0)

**Comment by Doraemon-DYX** [comment]
Hi, @sousoux 
I got the different result in both gap9_sdk & gap_sdk4.12:
(NNT mnist.onnx 0) dump 106.ppm -d -s -1
dump - input file ['106.ppm']
graph_executer - execute uncached: quantization mode none
/home/qy/anaconda3/envs/sdk4.12/lib/python3.8/site-packages/numpy/core/_methods.py:48: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
/home/qy/anaconda3/envs/sdk4.12/lib/python3.8/site-packages/numpy/core/_methods.py:48: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
/home/qy/gap_sdk4.12/tools/nntool/execution/kernels/float/fast_conv.py:113: RuntimeWarning: overflow encountered in multiply
  slabhw = np.multiply(in_tensor[cur_h * params.dilation.h:
/home/qy/gap_sdk4.12/tools/nntool/execution/kernels/float/fast_conv.py:128: RuntimeWarning: invalid value encountered in add
  result[out_c_i] += slabhw
/home/qy/gap_sdk4.12/tools/nntool/execution/kernels/float/fast_conv.py:113: RuntimeWarning: invalid value encountered in multiply
  slabhw = np.multiply(in_tensor[cur_h * params.dilation.h:
output_1t_1                                                           
      nan       nan       nan       nan       nan       nan       nan       nan       nan       nan
 
Can you tell me whichv ersion of sdk do you use？ And why qerror doesn't work?

**Comment by sousoux** [comment]
That one looks like the graph was not loaded with -q. "graph_executer -
execute uncached: *quantization mode none*"

**Comment by sousoux** [comment]
On qerror if you see a large error this is because the float values are
derived from the quantized tensors. Try with qerror 106.ppm
--compare_quantized.

**Comment by Doraemon-DYX** [comment]
@sousoux 
I'm sure that I use the command `open -q mnist.onnx`. Now, I'm confused about it. Maybe we use different version of sdk?

**Comment by sousoux** [comment]
I'm wondering about that as well. I am ahead of the latest gap9 version but this area in nntool has not been touched I think. At worst the next release should correct the behavious you are seeing.
