### ISSUE TITLE
Can't find a matching Convolution basic kernel

### ISSUE THREAD

**Issue by Doraemon-DYX** [GreenWaves-Technologies/gap_sdk#359]
In gap9_SDK, I encountered an error as following, it seems that autotiler Can't find a matching Convolution basic kernel:

![error](https://user-images.githubusercontent.com/74696799/200491250-8ce7c0e2-9783-4f0e-b8ea-6e12a2cfecc3.png)

**Comment by Yaooooo** [comment]
Please post GAP9 issues in GAP9 repository or send it to us by mail
