### ISSUE TITLE
SDK compilation error: pthread_yield() deprecated since glibc 2.34

### ISSUE THREAD

**Issue by m1karmida** [GreenWaves-Technologies/gap_sdk#360]
Hi,
I was trying to compile SDK with Ubuntu 22.04 but the compilation ends with an error regarding **pthread_yield()**  function used in different cpp files. Since glibc 2.34, this function is marked as deprecated. The linux suggests to replace with **sched_yield()** . 
This error is because of my ubuntu version or do you have to fixed it? 

Thank you

**Comment by Yaooooo** [comment]
Hi,

Yes, but it hasn't been pushed to the public version. 
The problem is because of this file: gvsoc/gvsoc/models/utils/dpi_wrapper_impl.cpp
Line 313
You can change it to sched_yield()
