### ISSUE TITLE
Is it possible for enabling multi-thread inference on GAP8

### ISSUE THREAD

**Issue by huzq85** [GreenWaves-Technologies/gap_sdk#361]
hi,
Recently I have been investigating whether we could enable the inference job by multi-threadings. I went through some examples (MoboileNet model from nn_menu), and found that all the inference tasks are single-threaded. Meanwhile, it looks like GAP8 platform could perform multi-threading tasks from the Helloworld example (`examples/gap8/basic/helloworld`).
As such, I am wondering if we could enable the multi-thread tasks when we are doing DNN inference.

**Comment by sousoux** [comment]
all kernels on gap are parallel. (the threads are cores and they are scheduled across all of them)

**Comment by huzq85** [comment]
> all kernels on gap are parallel. (the threads are cores and they are scheduled across all of them)

Got you. Thanks!
