### ISSUE TITLE
Autotiler: details about generation phase

### ISSUE THREAD

**Issue by m1karmida** [GreenWaves-Technologies/gap_sdk#366]
![mem_occupancy](https://user-images.githubusercontent.com/56913748/213396636-9baac54f-8f85-4c0b-94f9-72bd563aed82.png)

Hi, i would like to understand in deep the meaning of the parameters about this image captured after gentile execution (Baseline bandwidth, TIling bandwidth, etc).  Where Can i find it?

**Comment by sousoux** [comment]
L3 / L2 bandwidth - bytes transferred from/to L3 and L2 during network run
Tiling bandwidth overhead - amount of moves per parameter. Ideally you only want to move things once.
Baseline bandwidth - available memory bandwidth in all memory areas
% of baseline - amount of memory bandwidth consumed by network run
Sum of kernel operations - MAC estimate
