### ISSUE TITLE
Error(re-open): Custom network for Ai-deck

### ISSUE THREAD

**Issue by godhj93** [GreenWaves-Technologies/gap_sdk#369]
Hi, all

I raise this issue again because the previous issue had been closed too earlier.

I am trying to deploy custom neural networks to Ai-deck(crazyflie) and familiar with tensorflow and tensorflow lite but not NNtools.

I succeed the classification example for ai-deck, but When I try to my custom network, an error occurs.

one of my custom network's architecture is as follows:
```
class Encoder_tf(tf.keras.Model):
    
    def __init__(self, obs_shape):
        super().__init__()
        
        assert len(obs_shape) == 3
        
        self.repr_dim = 32 * 35 * 35 +(7*3)
        
        self.convnet = tf.keras.Sequential([
            tf.keras.layers.Conv2D(filters = 32, kernel_size = 3, strides = 2, activation='relu'),
            tf.keras.layers.Conv2D(filters = 32, kernel_size = 3, strides = 1, activation='relu'),
            tf.keras.layers.Conv2D(filters = 32, kernel_size = 3, strides = 1, activation='relu'),
            tf.keras.layers.Conv2D(filters = 32, kernel_size = 3, strides = 1, activation='relu'),
        ])     
        
        self.flatten = tf.keras.layers.Flatten()
        self.concat = tf.keras.layers.Concatenate()
        
    def call(self, x):
        #Input: 64x64x4
        (obs, drone_states) = x
        
        obs = obs / 255.0 - 0.5
        
        h = self.convnet(obs)
        h = self.flatten(h)
        
        drone_states = self.flatten(drone_states) # 9*9*32 = 2592
        print(h.shape)
        print(drone_states.shape)
        h = self.concat([h, drone_states])
        return h
       
```

and I run the command 

```
docker run --rm -v ${PWD}:/module aideck-with-autotiler tools/build/make-example examples/ai/classification clean model build image
```

the error  is too long so I attached a link to see it
(the link: https://godhj93.notion.site/github-issue-error-e39347a8562b4395a2a5e31bf9097948)

So far, I checked the concatenation layer and flatten layer are problem. when those layers are removed the command works well.

Is there any solution for my problem? 

Thanks

**Comment by sousoux** [comment]
Please check the errors listed in my last message.

**Comment by godhj93** [comment]
Hi @sousoux.
I have already read your advice and I am confused because the file such as "classification.c" which contains the errors is automatically generated in directory "BUILD_MODEL_SQ8BIT"  when I run the command 
```
docker run --rm -v ${PWD}:/module aideck-with-autotiler tools/build/make-example examples/ai/classification clean model build image
``` 
So i could not edit any code because the docker command refers and compiles the files which are automatically generated.

Do I misunderstand your advise?

thanks for help.
