### ISSUE TITLE
How to run custom object detection model on GVSOC

### ISSUE THREAD

**Issue by Seeth92** [GreenWaves-Technologies/gap_sdk#383]
Hi! 
I am pretty new to using GAP8/ GVSOC. I have trained a SSD Mobilenet V2 model on a custom dataset and have followed the steps indicated in the GAPflow youtube tutorial to get an optimized C code of the model. I have saved these files in a separate directory. Is there any way to integrate the files in this folder in 'GAP_SDK' directory. How do I run this model on GVSOC?

**Comment by Yaooooo** [comment]
You don't have to put them inside of SDK, once the env is configured, those app files are free to be put anywhere. 
You can also check these NN examples we have: 
https://github.com/GreenWaves-Technologies/nn_menu

Where you can see similar app as license_plate_recognition, where we use mobilenet+ssd as well.
