### ISSUE TITLE
Autotiler GCC compilation error

### ISSUE THREAD

**Issue by Seeth92** [GreenWaves-Technologies/gap_sdk#384]
Using GAPflow, I have generated an optimized "ATModel.c" code for my Mobilenet V2 model trained on a custom dataset. However, I am stuck on GCC compilation through which .mk files and .emul files are generated in order to be run on GVSOC/ GAP board. 

As mentioned in the youtube tutorial, I have used the following command:
`gcc SSDModel.c -g -o Gentile -I. -I${TILER_INC} -I${TILER_EMU_INC} -I${TILER_CNN_GENERATOR_PATH} -I${TILER_CNN_GENERATOR_PATH_SQ8} -I${NNTOOL_GENERATOR_PATH} -I${TILER_CNN_KERNEL_PATH} -I${TILER_CNN_KERNEL_PATH_SQ8} -I${NNTOOL_KERNELS_PATH} ${TILER_LIB} ${TILER_CNN_GENERATOR_PATH}/CNN_Generator_Util.c ${TILER_CNN_GENERATOR_PATH_SQ8}/CNN_Generators_SQ8.c ${NNTOOL_GENERATOR_PATH}/nntool_extra_generators.c`

I have the following errors:
```

gcc: error: /CNN_Generators_SQ8.c : No such file or directory
gcc: error: /CNN_Generator_Util.c: No such file or directory
gcc: error: /nntool_extra_generators.c: No such file or directory
```

1. Do I need to set the environment path for each of the variables: TILER_INC, TILER_EMU... etc? 
2. Also, I don't see the "nntool_extra_generators.c" script in the latest version of gap_sdk. I have been stuck on this for about two weeks. Any thoughts on this? Your responses would be really helpful :)

**Comment by sousoux** [comment]
You need to source the sourceme in the root of the SDK.
