### ISSUE TITLE
CNN_BasicKernels_NE16.c:925: undefined reference to `hal_cl_eu_event_mask_wait_and_clear'

### ISSUE THREAD

**Issue by gwgknudayanga** [GreenWaves-Technologies/gap_sdk#421]
Hi @Pafrak 

Could you please help me to solve this issue at the time of generating the project to run on gap8?
this happen when i am running the "res = G.execute_on_target( ..." part of the coco_object_detection on gap8 project.

/home/udayanga/Udaya_Research_stuff/2024_GAP8_work/coco_object_detection/test_run/BUILD/GAP8_V3/GCC_RISCV_FREERTOS//home/udayanga/gap_sdk/tools/autotiler_v3/CNN_Libraries_NE16/CNN_BasicKernels_NE16.o: In function `KerConvDW3x3Stride1_NE16':
/home/udayanga/gap_sdk/tools/autotiler_v3/CNN_Libraries_NE16/CNN_BasicKernels_NE16.c:861: undefined reference to `hal_cl_eu_event_mask_wait_and_clear'
/home/udayanga/gap_sdk/tools/autotiler_v3/CNN_Libraries_NE16/CNN_BasicKernels_NE16.c
:861: undefined reference to `hal_cl_eu_event_mask_wait_and_clear'
/home/udayanga/Udaya_Research_stuff/2024_GAP8_work/coco_object_detection/test_run/BUILD/GAP8_V3/GCC_RISCV_FREERTOS//home/udayanga/gap_sdk/tools/autotiler_v3/CNN_Libraries_NE16/CNN_BasicKernels_NE16.o: In function `KerConv3x3Stride2_NE16':
/home/udayanga/gap_sdk/tools/autotiler_v3/CNN_Libraries_NE16/CNN_BasicKernels_NE16.c:925: undefined reference to `hal_cl_eu_event_mask_wait_and_clear'
/home/udayanga/gap_sdk/tools/autotiler_v3/CNN_Libraries_NE16/CNN_BasicKernels_NE16.c:925: undefined reference to `hal_cl_eu_event_mask_wait_and_clear'
/home/udayanga/gap_sdk/tools/autotiler_v3/CNN_Libraries_NE16/CNN_BasicKernels_NE16.c:925: undefined reference to `hal_cl_eu_event_mask_wait_and_clear'
/home/udayanga/Udaya_Research_stuff/2024_GAP8_work/coco_object_detection/test_run/BUILD/GAP8_V3/GCC_RISCV_FREERTOS//home/udayanga/gap_sdk/tools/autotiler_v3/CNN_Libraries_NE16/CNN_BasicKernels_NE16.o:/home/udayanga/gap_sdk/tools/autotiler_v3/CNN_Libraries_NE16/CNN_BasicKernels_NE16.c:925: more undefined references to `hal_cl_eu_event_mask_wait_and_clear' follow

collect2: error: ld returned 1 exit status

Thanks and Rgds,
Udayanga

**Comment by gwgknudayanga** [comment]
@marco-fariselli  could you please help me in this regard?

**Comment by marco-fariselli** [comment]
Hi !! It seems you are using the NE16 feature on GAP8. That piece of HW is available only on GAP9. I suggest you to remove the use_ne16=True from the quantization options.

**Comment by gwgknudayanga** [comment]
Yes It worked. Thank you so much.
