### ISSUE TITLE
Camera picture

### ISSUE THREAD

**Issue by peternomikos** [GreenWaves-Technologies/gap_sdk#55]
Hi 

I haven't quite understood if the moment I capture an Image I can use it for say with the algorithm of Mnist or is any further processing required?

Regards,

Peter

**Comment by Yaooooo** [comment]
Hi,

Of cause you can. You can try, for example, copy the image to Mnist or other application to try.
But, you are right, we will put a Mnist application with camera. 

Best,
Yao
