### ISSUE TITLE
UART Connection

### ISSUE THREAD

**Issue by peternomikos** [GreenWaves-Technologies/gap_sdk#56]
Hi 

I want to transfer data from my Gap8 to the computer through a UART module but I have some issues so far. I am not sure if the pins I choose are correct because in the users manual are not connected anywhere . I connected them according to the Arduino Uno. Also I am not sure with what to fill the entry itf entry of the config structure and the device name for the uart_open function.

Thank you for your time

Panagiotis

**Comment by Yaooooo** [comment]
Hi, 

Actually, on the GAPuino, the uart of GAP8 is connected to the FTDI chip. And the pinout has not been connected by default.
Therefore, for using the UART pin on GAPuino, some hardware modifications are necessary:
1, You need to disconnect the R9 and R36, and connect R37 and R39:  

  | UART | I2S
-- | -- | --
R9 | Unconnected | 0 ohm
R36 | Unconnected | 0 ohm
R37 | 0 ohm | Unconnected
R38 | Unconnected | Unconnected
R39 | 0 ohm | Unconnected

![image](https://user-images.githubusercontent.com/4712667/59437032-10ccc200-8df1-11e9-84fa-24de1c777536.png)

![image](https://user-images.githubusercontent.com/4712667/59437043-16c2a300-8df1-11e9-8e6f-8bf2672171ef.png)

![image](https://user-images.githubusercontent.com/4712667/59437056-1c1fed80-8df1-11e9-8530-3f6b803eee98.png)

We are sincerely sorry for that inconvenience.

Yao

**Comment by jinhuang01** [comment]
Hi, I am a little confused about the second and third images on this issue - is that we should also disconnect R41 and R40 to use UART module?

**Comment by jinhuang01** [comment]
Also, if I want use GAP8 with Bluetooth Low Energy, should I also do the above hardware modifications, too? Thank you very much.

**Comment by Pafrak** [comment]
Hi jinhuang01,
 on which board you want to use the BLE? do you want to connect a shield to Gapuino?
