### ISSUE TITLE
Difference between the Multiscale Pedestrian Detection and the Pedestrian Detection (HoG)

### ISSUE THREAD

**Issue by eliasph88** [GreenWaves-Technologies/gap_sdk#69]
Is there any diference between these given applications?
In the link:
https://greenwaves-technologies.com/manuals/BUILD/APPLICATIONS/html/index.html#section0
They are treated as different but then the description is exactly the same and none of them has a path or even the name of the c file to search in the sdk folder for it.
In fact, of the 6 applications provided in the link:
Canny Edge Detection. Has a "What in this folder" but no path.
Multiscale Pedestrian Detection. Does not have a "What in this folder", "Structure of the directory" or the path to it.
CIFAR10 image recognition. This one does have a "Structure of the directory" section which also includes the path.
Face Detection. Does not have a "What in this folder", "Structure of the directory" or the path to it (Althoug is the only on facedetection in the application folder)
Pedestrian Detection (HoG): Does have a "Structure of the directory" section" but not the path to it which if is gap_sdk/applications/MultiScalePedestrianDetector then which one is the path for the other one?
MNIST image recognition Does have a "Structure of the directory" but no path.

**Comment by Pafrak** [comment]
Dear eliasph88,
 sorry for the late answer. This happened because the documentation that we have inside single folders has been copied to general sdk documentation. Now all the applications are in the applications folder in the root of the SDK.
