### ISSUE TITLE
Makefile and Code to generate C files for KWS Demo

### ISSUE THREAD

**Issue by anujdutt9** [GreenWaves-Technologies/gap_sdk#81]
Hi. Can you please provide the Makefile and any other files required to generate the C files for the KWS demo trained on custom dataset?
Thanks.

**Comment by Pafrak** [comment]
Hi Anuj Dutt,
 we are working to provide it within NNtool.

**Comment by PaulLuperini** [comment]
@Pafrak What is the status of this issue ? Is it solved ? Can we close it ?

**Comment by Pafrak** [comment]
We released few time ago a project showing how to go from wav files onto GAP [here](https://github.com/GreenWaves-Technologies/kws/tree/master).

We will also integrated the preprocessing into gap kernels in next sdks releases.
