### ISSUE TITLE
Scope of NNTOOL

### ISSUE THREAD

**Issue by chauhansaurabhb** [GreenWaves-Technologies/gap_sdk#85]
Hello,

I am looking for the scope of the NNTOOL. I tried to transfer/deploy SSD tensorflow lite model and Facenet Keras model using facenet.h5 file but both didn't work. It seems that corresponding functions (i.e. kernals) are not implemented.

Could you please provide me the scope of the NNTOOL or pointer? What kind of model can I deploy on the edge device? How can I perform only inference using the pre-trained model using gap_sdk?

How can I realize the face recognition or object detection (using SSD) application using gap_sdk? 

Thanking you!

**Comment by sousoux** [comment]
Hi, I'll send you a PM on this.
