### ISSUE TITLE
FaceDetection failed

### ISSUE THREAD

**Issue by DonQuixote-lab** [GreenWaves-Technologies/gap_sdk#97]
I have tested the CannyEdgeDetection application successfully.But the FaceDetection failed.

![e2361edd9d576b3b5e29bee8c2c4716](https://user-images.githubusercontent.com/58680257/71889551-54b45980-317d-11ea-944b-3af68dc2975e.png)

There is also a problem when I run the FaceDetection on the gvsoc platform,

![d92a7154733dee2a91187746f050881](https://user-images.githubusercontent.com/58680257/71866651-e3a38080-3141-11ea-8b77-c04855b208d6.png)

What should I do?

**Comment by Toxic-Scofield** [comment]
You should think more，don't just ask when you meet problems.

**Comment by DonQuixote-lab** [comment]
> You should think more，don't just ask when you meet problems.

**Comment by DonQuixote-lab** [comment]
> You should think more，don't just ask when you meet problems.

**Comment by DonQuixote-lab** [comment]
When openocd uesed by application,no problems appear. But when I use plpbridge,files can not loaded from pc.

**Comment by Yaooooo** [comment]
Hi,

If you are using the last version of SDK, we have updated this application to use filesystem api (in ImgIO.c), which provided by PMSIS. These api supports only openOCD.  
In the future, we will remove plpbridge step by step, and maintain only openOCD.

Best,
Yao

**Comment by DonQuixote-lab** [comment]
Hi
I am using the last version of SDK.I have executed the WaterMeter and CannyEdgeDetection with no problem.But the BilinearResize failed 
![e1282f2b376246a4050b723b2472aca](https://user-images.githubusercontent.com/58680257/72031075-3ad25e00-32c6-11ea-8882-fbc72d60eac1.png)
PLPBRIDGE_FLAGS += -fileIO 2

**Comment by Yaooooo** [comment]
Thank you for report, you are right, there's a regression on this example because of the update. 
We will fix it asap.

**Comment by Yaooooo** [comment]
I have fixed it and pushed. 
Please pull the last commit and retry.
